### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by sehamid** [CKOTech/checkout-whmcs-plugin#3]
checkoutjs_callback.php file requires following files 

include("../../../init.php");
include("../../../includes/functions.php");
include("../../../includes/gatewayfunctions.php");
include("../../../includes/invoicefunctions.php");
include ("../includes/model/methods/creditcard.php");

But the only file exist is /includes/model/methods/creditcard.php 

Can you please provide other files as well because we are facing the issue while payment is being made and redirecting after payment is done.

Issue reference : https://www.screencast.com/t/Ywoagleh

**Comment by nicolas-maalouf-cko** [comment]
Hi @sehamid these files are normally part of WHMCS and not our module 

We will be deprecating our WHMCS extension, are you currently using it on your live store?
